name: phylophlan
description: write your description here
keywords:
  - phylogenetic
  - microbial
  - genomes
  - metagenomes
tools:
  - phylophlan:
      description: Precise phylogenetic analysis of microbial isolates and genomes from metagenomes
      homepage: "https://huttenhower.sph.harvard.edu/phylophlan"
      documentation: "https://github.com/biobakery/biobakery/wiki/PhyloPhlAn3"
      tool_dev_url: "https://github.com/biobakery/phylophlan"
      doi: "10.1038/s41467-020-16366-7"
      licence: ['MIT License']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta_genomes:
      type: file
      description: fasta file
      pattern: "*.{fasta.gz,fasta,fa.gz,fa}"
        e.g. [ id:'test', single_end:false ]
  - phylophlan_configuration_file:
      type: file
      description: phylophlan configuration file following pattern described on manual
      pattern: "*.{cfg}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - raxml_tre:
      type: file
      description: Phylogenetic tree built with raxml
      pattern: "*.{tre}"
  - aln:
      type: file
      description: Fasta alignment file
      pattern: "*.{aln}"
  - tre:
      type: file
      description: Phylogenetic tree built with FastTree
      pattern: "*.{tre}"


authors:
  - "@Mxrcon"
