name: admixture
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - sort
tools:
  - admixture:
      description: ADMIXTURE is a software tool for maximum likelihood estimation of individual ancestries from multilocus SNP genotype datasets.
      homepage: http://dalexander.github.io/admixture/
      documentation: http://dalexander.github.io/admixture/admixture-manual.pdf
      tool_dev_url: http://dalexander.github.io
      doi: "10.1101/gr.094052.109"
      licence: ['Free for Academic Use']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: Bed file
      pattern: "*.{bed,ped}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  ## TODO nf-core: Delete / customise this example output
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

authors:
  - "@abhi18av"
  - "@Mxrcon"
